import { Roboto } from 'next/font/google'
import './globals.css'; 
import { Header } from '@/components/Header/Header';
import { Footer } from '@/components/Footer/Footer';
import { StoreProvider } from '@/redux/StoreProvider';

const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin', 'cyrillic'],
  display: 'swap',
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru" className={roboto.className}>
      <body>
        <StoreProvider>
          <Header />

          <main className='main'>
            {children}
          </main>

          <Footer />
        </StoreProvider>
      </body>
    </html>
  )
}
